### ISSUE TITLE
Add macro to disable OpenCL defines?

### ISSUE THREAD

**Issue by nicknytko** [luspi/tausch#2]
https://github.com/luspi/tausch/blob/9d7663a68a4b92b11c158c39b4b13333e6f5076e/tausch.h#L73-L105

How important are these target versions for Tausch?  I have these defined in another file in my project and the compiler gets mad when I import `tausch.h` afterwards -- could we have a `TAUSCH_OPENCL_NOINCLUDES` or similar macro to turn this block of code off?

**Comment by luspi** [comment]
Sure, as long as you take care of the right includes yourself before including the Tausch header, then they don't _need_ to happen here.

**Comment by luspi** [comment]
Added with f0f349cc90dc38ed953a97dc031e7ef153a172ff
